services:
  - type: web
    name: minesweeper-tg
    env: node
    buildCommand: |
      npm install
      cd client && npm install
      cd ..
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true