services:
  - type: web
    name: minesweeper-tg
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
    autoDeploy: true
    disk:
      name: minesweeper-data
      mountPath: /data
      sizeGB: 1